export const CITY_NAMES = [
  "Nevşehir",
  "Bursa",
  "Çanakkale",
  "İzmir",
  "Antalya",
  "İstanbul",
  "Ankara",
  "Aydın",
  "Balıkesir",
  "Muğla",
];

export const RESTAURANT_CUISINES = [
  "Tıbbi gıdalar",
  "Akdeniz",
  "Venezuela",
  "Amerikan Yerli",
  "Güney İtalya",
  "Avrupa",
  "Nijerya",
  "Sri Lankalı",
  "Brezilya",
  "Biftek Restoranı",
  "Alman",
  "Japon Füzyonu",
  "Meksika",
  "Romanya",
  "Hawai",
  "Campania",
  "İspanyol",
  "İtalyan",
  "İskoç",
  "Fujian",
  "Latin",
  "Pizza",
  "Filipinler",
  "Ekvador",
  "Kosta Rika",
  "Kolombiya",
  "Arap",
  "Asur",
  "Füzyon",
  "Türk",
  "Yemekli barlar",
  "Ermeni",
  "Jamaika",
  "İskandinav",
  "İsviçre",
  "Kuzey İtalya",
  "Ortadoğu",
  "Japon tatlı dükkânı",
  "Lübnan",
  "Lombard",
  "Güneybatı",
  "Felemenk",
  "Rus",
  "Mangal",
  "Cajun ve Creole",
  "Yunan",
  "Bira restoranları",
  "Hırvat",
  "Polonya",
  "Etiyopya",
  "Endonezya",
  "Sokak Yemekleri",
  "Barbekü",
  "Katalan",
  "Yunnan",
  "Fas",
  "Tayvan",
  "Avusturya",
  "İran",
  "Asya",
  "Sağlıklı",
  "Çin",
  "Fast Food",
  "Doğu Avrupa",
  "Deniz Mahsülleri",
  "Gürcü",
  "Brew Pub",
  "Bar",
  "Azerbaycan",
  "Kafe",
  "Fransız",
  "Emilia",
  "Liguria",
  "Şarküteri",
  "Xinjiang",
  "Moğol",
  "Sloven",
  "Şili",
  "Afrika",
  "Danimarka",
  "Vietnam",
  "Arjantin",
  "Suşi",
  "Peru",
  "Karayipler",
  "Portekiz",
  "Balti",
  "Çorbalar",
  "Shojin",
  "Ukrayna",
  "İsveç",
  "Şarap Barı",
  "Tunus",
  "Güney Amerika",
  "Polinezya",
  "Macar",
  "Lokanta",
  "Malezya",
  "Napoli",
  "Arnavut",
  "Pekin mutfağı",
  "Belçika",
  "Sicilya",
  "Kafkas",
  "İrlanda",
  "Amerikan",
  "Yöresel",
  "İsrail",
  "Pakistan",
  "Avustralya",
  "Özbek",
  "Cezayir",
  "Lazio",
  "Letonya",
  "Guatemala",
  "Orta Asya",
  "Norveç",
  "Küba",
  "Hint",
  "Çağdaş",
  "Orta İtalya",
  "Kore",
  "Gastropub",
  "Japon",
  "Orta Amerika",
  "Romana",
  "Afkan",
  "Kanada",
  "Bahama",
  "İngiliz",
  "Orta Avrupa",
  "Toskana",
  "Tibet",
  "Nepal",
  "Sardinya",
  "Kyoto mutfağı",
  "Çek",
  "Meyve dükkânları",
  "Kamboçya",
  "Mısır",
  "Tayland",
  "Bangladeş",
  "Gal",
  "Uluslararası",
];

export const HOTEL_AMENITY_GROUPS = [
  {
    groupName: "İşletme Olanakları",
    amenities: [
      "Spor Salonlu/Spor Odalı Fitness Merkezi",
      "Spa",
      "Masaj",
      "Hamam",
      "Sauna",
      "Yüzme havuzu (Açık havuz, Kapalı havuz, Çocuk havuzu, Isıtmalı havuz, Kaplıca havuzu, Sığ kısmı bulunan havuz, Tuzlu su havuzu, Çatı havuzu, Özel havuz)",
      "Plaj",
      "Özel plaj",
      "Restoran",
      "Bar/oturma salonu",
      "Kahve dükkanı",
      "Çocuk kulübü",
      "Çocuk Aktiviteleri (Çocuğa/Aileye Uygun)",
      "Çocuklar için oyun alanı",
      "Oyun salonu",
      "Bilardo",
      "Bowling",
      "Casino ve Talih Oyunları",
      "Su parkı",
      "Jakuzi",
      "Solaryum",
      "İş merkezi (İş merkezinde fotokopi/faks, İş merkezinde ücretsiz kablosuz ağ, İş merkezinde ücretsiz kablolu internet)",
      "Konferans salonu",
      "Toplantı odaları",
      "Ücretsiz internet",
      "Ücretsiz Yüksek Hızda İnternet (WiFi)",
      "Çamaşır yıkama hizmeti",
      "Kuru temizleme",
      "Self servis çamaşırhane",
      "Ücretsiz otopark",
      "Yakınlarda halka açık ücretsiz otopark",
      "Cadde üzerinde park",
      "Tesis içinde ücretli özel otopark",
      "Yakınlarda ücretsiz özel otopark",
      "Güvenli otopark",
      "Evcil Hayvan Kabul Edilir (Köpeğe/Evcil Hayvanlara İzin Verilir)",
      "Concierge",
      "Bagaj saklama hizmeti",
      "Vale park hizmeti",
      "Döviz bozdurma",
      "24 saat açık resepsiyon",
      "Havaalanı ulaşım hizmeti",
      "Ücretsiz havaalanı ulaşım hizmeti",
      "Taksi servisi",
      "Servis otobüsü hizmeti",
      "Ücretsiz servis veya taksi hizmetleri",
      "Hediyelik eşya dükkanı",
      "Market",
      "Dükkanlar",
    ],
  },
  {
    groupName: "Oda özellikleri",
    amenities: [
      "Ücretsiz internet",
      "Ücretsiz Yüksek Hızda İnternet (WiFi)",
      "Kablolu/uydu bağlantılı TV",
      "Video oyun konsolu",
      "DVD’ler",
      "iPod yuvası",
      "Düz Ekran Televizyon",
      "Klima",
      "Isıtmalı havuz",
      "Küçük mutfak",
      "Elektrikli su ısıtıcısı",
      "Kahve/çay makinesi",
      "Mikrodalga fırın",
      "Buzdolabı",
      "Mutfak eşyaları",
      "Fırın",
      "Çamaşır makinesi",
      "Çamaşır kurutma makinesi",
      "Ütü",
      "Self servis çamaşırhane",
      "Ses geçirmez odalar",
      "Karartma perdeleri",
      "Bornoz",
      "Ücretsiz banyo ve kişisel bakım malzemeleri",
      "Saç kurutma makinesi",
      "Jakuzili küvet",
      "Yerle aynı hizada duş",
      "Kasa",
      "Dizüstü bilgisayar kasası",
      "Bebek sandalyesi mevcut",
      "Puset",
      "Ortak mutfak",
      "Ortak oturma/televizyon izleme alanı",
    ],
  },
  {
    groupName: "Oda türleri",
    amenities: [
      "Ayrı oturma odası",
      "Ayrı yemek salonu",
      "Süitler",
      "Aile odaları",
      "Balayı süiti",
      "Birbirine açılan odalar mevcut",
      "Sigara içilebilen odalar mevcut",
      "Sigara içilmeyen odalar",
      "Özel balkon",
      "Çatı katı terası",
      "Ortak banyo",
      "Özel banyolar",
      "Allerjensiz oda",
      "Yalnızca yetişkinler için",
    ],
  },
];

export const HOTEL_AMENITIES = [
  "Radyo",
  "İnternet",
  "Çocuklara ücretsiz konaklama",
  "Çocuk Aktiviteleri (Çocuğa/Aileye Uygun)",
  "Ismarlanabilen filmler",
  "Bisiklet kiralama",
  "Dağ manzaralı",
  "Oda hizmeti",
  "Bulaşık makinesi",
  "Ücretsiz internet",
  "Lostra",
  "Şehir manzaralı",
  "Ayrı oturma odası",
  "Kapalı havuz",
  "Çocuklar için kitaplar",
  "Dalış",
  "Okyanus manzarası",
  "Ayrı yemek salonu",
  "Çocuk yemekleri",
  "Çamaşır kurutma makinesi",
  "Özel balkon",
  "Barbekü alanları",
  "Ortak mutfak",
  "Cibinlik",
  "Concierge",
  "Bisiklet mevcut",
  "Masaj",
  "Kuru temizleme",
  "Birbirine açılan odalar mevcut",
  "DVD’ler",
  "İnternet Bağlantılı İş Amaçlı Bölüm",
  "Ses geçirmez odalar",
  "Buzdolabı",
  "Çocuklara uygun büfe",
  "Çocuklar için oyun alanı",
  "Ücretsiz Yüksek Hızda İnternet (WiFi)",
  "Güneşlenme alanı",
  "Çamaşır yıkama hizmeti",
  "Yakınlarda halka açık ücretsiz otopark",
  "Cadde üzerinde park",
  "Kablolu/uydu bağlantılı TV",
  "Balık tutma",
  "Evcil Hayvan Kabul Edilir (Köpeğe/Evcil Hayvanlara İzin Verilir)",
  "Uyandırma servisi/çalar saat",
  "Sauna",
  "Bahçe",
  "Spor Salonlu/Spor Odalı Fitness Merkezi",
  "Servis otobüsü hizmeti",
  "Ekstra uzun yataklar",
  "Bagaj saklama hizmeti",
  "Bornoz",
  "Jakuzili küvet",
  "Piknik alanı",
  "İş merkezinde fotokopi/faks",
  "Saç kurutma makinesi",
  "Tam vücut masajı",
  "Masa tenisi",
  "Hızlı giriş/çıkış",
  "Yetişkin havuzu",
  "Set Üstü Ocak",
  "Tekne turu",
  "Hava temizleme cihazı",
  "Çocuklar için açık hava oyun ekipmanı",
  "Banyo/duş",
  "Revir",
  "Bebek sandalyesi mevcut",
  "Gece Kulübü/DJ",
  "Gece eğlencesi",
  "Puset",
  "Kahvaltı mevcut",
  "Dizüstü bilgisayar kasası",
  "Şezlonglar/plaj sandalyeleri",
  "Tesis içi ATM",
  "Klima",
  "Ortak oturma/televizyon izleme alanı",
  "Küçük mutfak",
  "Ücretsiz Hazır Kahve",
  "Balayı süiti",
  "Spa",
  "Rüzgar sörfü",
  "Yerle aynı hizada duş",
  "Bebek bakımı",
  "Havaalanı ulaşım hizmeti",
  "Yemek salonu",
  "Isıtmalı havuz",
  "Çalışma masası",
  "Görevli odası",
  "Araba kiralama",
  "Konferans salonu",
  "Çocuklara uygun televizyon kanalları",
  "Çatı barı",
  "Hamam",
  "Gazete",
  "Çamaşır makinesi",
  "Karo/mermer zemin",
  "Ayak masajı",
  "Bisiklet turları",
  "Gardırop/elbise dolabı",
  "Çatı katı terası",
  "Elbise askısı",
  "Ek banyo",
  "İndirimli içki saati",
  "Müzikler",
  "Simgesel nokta manzarası",
  "Market",
  "Hediyelik eşya dükkanı",
  "Fitness/spa soyunma odaları",
  "Güneş şemsiyeleri",
  "Alerjensiz oda",
  "Aile odaları",
  "Telefon",
  "Şişe suyu",
  "Kasa",
  "Havuz kenarı barı",
  "Doğa yürüyüşü",
  "Açık havuz",
  "Döviz bozdurma",
  "VIP oda olanakları",
  "Dart",
  "Oturma alanı",
  "Düz Ekran Televizyon",
  "Oyun salonu",
  "İlk yardım çantası",
  "Kahve dükkanı",
  "Ütü hizmeti",
  "Dükkanlar",
  "Güvenli otopark",
  "Ücretsiz çay",
  "Şömine",
  "Açık hava şöminesi",
  "Katlı otopark",
  "Açık büfe kahvaltı",
  "Mikrodalga fırın",
  "Elektrikli su ısıtıcısı",
  "Ücretsiz banyo ve kişisel bakım malzemeleri",
  "Bar/oturma salonu",
  "Vale park hizmeti",
  "Mini bar",
  "Sigara içilebilen odalar mevcut",
  "Buhar odası",
  "Yakınlarda ücretli halka açık otopark",
  "Jakuzi",
  "Özel havuz",
  "Ücretli Wi-Fi",
  "Güneşlenme terası",
  "24 saat giriş olanağı",
  "Odaya kahvaltı",
  "Şemsiye",
  "Özel banyolar",
  "Otomat",
  "Salon",
  "Tesis içinde ücretli özel otopark",
  "24 saat açık resepsiyon",
  "Kahve/çay makinesi",
  "Açık hava yemek salonu",
  "Özel giriş/çıkış",
  "Süitler",
  "Yakı",
];
