export const CITY_NAMES = [
  "Nevşehir",
  "Bursa",
  "Çanakkale",
  "İzmir",
  "Antalya",
  "Istanbul",
  "Ankara",
  "Aydın",
  "Balıkesir",
  "Muğla",
];

export const RESTAURANT_CUISINES = [
  "Southwest",
  "Dining Bars",
  "Contemporary",
  "Georgian",
  "Nigerian",
  "South America",
  "Bangladesh",
  "Wine Bar",
  "Sweden",
  "Vegeterian",
  "Cuban",
  "Greek Food",
  "nan",
  "Turkish Food",
  "Cambodia",
  "Ireland",
  "Soups",
  "Kyoto Cuisine",
  "Czech",
  "Portugal",
  "Korean",
  "Colombia",
  "Vegan",
  "Ukraine",
  "Lombardy",
  "Meat",
  "Lebanese",
  "Latvia",
  "Croatian",
  "Chinese",
  "Campania",
  "Café",
  "Deli",
  "Algeria",
  "Fujian",
  "Latin",
  "Pizza",
  "African Food",
  "Nepalese",
  "Malaysia",
  "English",
  "Beer Restaurants",
  "Mediterranean Food",
  "Philippines",
  "Asian food",
  "Naples",
  "Guatemalan",
  "Scandinavian",
  "Barbecue",
  "American",
  "Northern Italy",
  "Japanese",
  "Slovenian",
  "Japanese Sweets Shop",
  "Israeli",
  "Galician",
  "Eastern Europe",
  "Chicken",
  "Australia",
  "Polynesia",
  "Hungarian",
  "Caucasian",
  "Restaurant",
  "Catalan",
  "Street Food",
  "German",
  "Scottish",
  "Yunnan",
  "Peruvian",
  "Belgium",
  "Bahamian",
  "Roman",
  "Vietnamese",
  "Afghan",
  "Central Europe",
  "Taiwan",
  "Native American",
  "Central America",
  "Steakhouse",
  "Fusion",
  "Healthy foods",
  "Fast Food",
  "Medical Foods",
  "Latin American Food",
  "Uzbek",
  "Dutch",
  "Brew Pub",
  "Spanish",
  "Indian",
  "Hawaii",
  "Beijing Cuisine",
  "French",
  "Sushi",
  "Alcohol",
  "Thai",
  "Central Asia",
  "Canada",
  "Emilia",
  "Liguria",
  "Xinjiang",
  "Russian",
  "Southern Italy",
  "Argentina",
  "European Cuisine",
  "Venezuelan",
  "Mongolian",
  "Azerbaijan",
  "Indonesian",
  "Central Italy",
  "Arab",
  "International",
  "Chile",
  "Balti",
  "Shojin",
  "Denmark",
  "Italian Food",
  "Sri Lankan",
  "Gluten Free",
  "Switzerland",
  "Ecuador",
  "Albanian",
  "Norway",
  "Pakistan",
  "Armenian",
  "Romania",
  "Lazio",
  "Brazil",
  "Assyrian",
  "Austria",
  "Ethiopia",
  "Egyptian",
  "Caribbean",
  "Fruit",
  "Fish",
  "Grill",
  "Tunisia",
  "Gastropub",
  "Jamaican",
  "Sardinia",
  "Sicily",
  "Iranian",
  "Morocco",
  "Middle East Food",
  "Tibet",
  "Mexican Food",
  "Poland",
  "Japanese Fusion",
  "Tuscany",
  "Costa Rica",
  "Local",
];

export const HOTEL_AMENITY_GROUPS = [
  {
    groupName: "Room and Accommodation Features",
    amenities: [
      "Extra long beds",
      "Safe",
      "Wardrobe/closet",
      "Dining room",
      "Private pool",
      "Electric kettle",
      "Private entrance/exit",
      "Additional bathroom",
      "Family rooms",
      "Hypoallergenic room",
      "Flat-screen TV",
      "Seating area",
      "VIP room amenities",
      "Baby high chair available",
      "Private balcony",
      "Non-smoking rooms",
      "Smoking rooms available",
      "Interconnecting rooms available",
      "Suites",
      "Air conditioning",
      "Iron",
      "Washing machine",
      "Mosquito net",
      "Blackout curtains",
      "Bathrobes",
      "Tile/marble floor",
      "Iconic point view",
      "Clothes rack",
      "Outdoor bath",
      "Honeymoon suite",
      "Laptop safe",
      "iPod dock",
      "Work desk",
      "Separate living room",
      "Walk-in shower",
      "Private bathrooms",
      "Soundproof rooms",
      "Hot spring bath",
    ],
  },
  {
    groupName: "Dining and Kitchen Amenities",
    amenities: [
      "Restaurant",
      "Special diet menus",
      "Room service",
      "Coffee/tea maker",
      "Coffee shop",
      "Picnic area",
      "Poolside bar",
      "Free tea",
      "Oven",
      "Small kitchen",
      "Kitchenware",
      "Dishwasher",
      "Stovetop",
      "BBQ areas",
      "Free Instant Coffee",
      "Breakfast in room",
      "Free breakfast",
      "Buffet breakfast",
      "Buffet suitable for children",
      "Outdoor dining area",
      "Children's meals",
      "Shops",
    ],
  },
  {
    groupName: "Leisure, Sports, and Recreation",
    amenities: [
      "Game room",
      "Children's play area",
      "Infinity pool",
      "Children's pool",
      "Skiing",
      "Nature walk",
      "Multi-storey parking",
      "Karaoke",
      "Evening entertainment",
      "Adults only",
      "Beach",
      "Rooftop pool",
      "Pool",
      "Ski rental",
      "Adult pool",
      "Water slide",
      "Parking",
      "Canoeing trip (off-site)",
      "Fishing",
      "Water park (off-site)",
      "Sunbathing terrace",
      "Market",
      "Canoeing",
      "Indoor pool",
      "Turkish bath",
      "Mini golf",
      "Tennis court",
      "Tennis court (off-site)",
      "Jacuzzi",
      "Bowling",
      "Table tennis",
      "Nightclub/DJ",
      "Squash (off-site)",
      "Garden",
      "Diving",
      "Outdoor play equipment for children",
      "Ocean view",
      "Shared lounge/TV area",
      "Board games/puzzles",
      "Video game console",
      "Yoga room",
      "Fitness center with gym/workout room",
      "Outdoor pool",
      "Water sports equipment rental",
      "Bicycle rental",
      "Horse riding",
      "Archery (off-site)",
      "Windsurfing",
      "Private beach",
      "Yoga classes",
      "Boat tour",
      "Bicycle tours",
      "Golf course",
      "Casino and Gambling",
      "Outdoor furniture",
      "Pool with a view",
      "Mountain view",
      "Darts",
      "Radio",
      "Music",
      "Books for children",
      "Ski-in/ski-out",
      "Bicycles available",
      "Indoor play area for children",
      "Snorkeling",
      "Shallow pool",
      "Swimming pool toys",
      "Jacuzzi bathtub",
      "Fireplace",
      "Children's Activities (Kid/Family-friendly)",
      "City view",
      "Sun terrace",
      "Ski school",
      "Badminton",
      "Bar/lounge",
      "Fitness classes",
      "Swim-up bar",
      "Happy hour",
      "Saltwater pool",
      "Rooftop terrace",
    ],
  },
  {
    groupName: "Wellness and Health Services",
    amenities: [
      "Pedicure",
      "Head massage",
      "Solarium",
      "Waxing services",
      "Hand massage",
      "Steam room",
      "Self-service laundry",
      "Express check-in/check-out",
      "Door attendant",
      "Animation team",
      "Shuttle bus service",
      "Infirmary",
      "Pool/beach towels",
      "Full body massage",
      "Foot massage",
      "Lounge",
      "First aid kit",
      "Stroller",
      "Wine/champagne",
      "Sauna",
      "Makeup services",
      "Neck massage",
      "Massage chair",
      "Duty room",
      "Facials",
      "Wake-up service/alarm clock",
      "Spa",
      "Fitness/spa changing rooms",
      "Luggage storage service",
      "Vending machine",
      "Electric vehicle charging station",
      "Babysitting",
      "Non-smoking hotel",
      "Free toiletries and personal care products",
      "Dry cleaning",
      "Air purifier",
      "Sun umbrellas",
      "Manicure",
      "Massage",
      "Butler service",
      "Water park",
    ],
  },
  {
    groupName: "Services and Utilities",
    amenities: [
      "24-hour front desk",
      "Laundry service",
      "Concierge",
      "Paid Wi-Fi",
      "Paid internet",
      "Free shuttle or taxi services",
      "Free stay for children",
      "Currency exchange",
      "Shuttle bus service",
      "Self-service laundry",
      "24-hour check-in option",
      "Free High-Speed Internet (WiFi)",
      "Free parking",
      "On-site private parking (surcharge)",
      "Valet parking service",
      "Public Wi-Fi",
      "On-site paid public parking",
      "Free Wi-Fi at the business center",
      "Wi-Fi",
      "Free Wi-Fi at the business center",
      "Iron",
      "Free wired internet in the business center",
      "Breakfast available",
      "Pets allowed (Dogs/Pets Allowed)",
      "City view",
      "Street parking",
      "Telephone",
      "Hair Dryer",
      "Clothes dryer",
      "Private lounge facility",
      "Mini bar",
      "Nearby public free parking",
      "Free nearby private parking",
      "Nearby paid private parking",
      "Nearby paid public parking",
      "Free airport transportation",
      "DVDs",
      "Electric blanket",
      "Taxi service",
      "Shared kitchen",
      "24-hour security",
      "Secure parking",
      "Aerobics",
      "Dry cleaning",
      "Meeting rooms",
      "Sun loungers/beach chairs",
      "Conference room",
      "Internet",
      "Photocopy/fax services at the business center",
      "Kids' club",
      "Rooftop bar",
      "Free High-Speed Internet (WiFi)",
      "Sofa",
      "Wi-Fi",
      "Newspaper",
      "Complimentary welcome drink",
      "Ironing service",
      "Business section with internet access",
      "Car rental",
      "Airport transportation service",
      "On-site ATM",
    ],
  },
];

export const HOTEL_AMENITIES = [
  "Game room",
  "Children's play area",
  "Pedicure",
  "Infinity pool",
  "Head massage",
  "Squash",
  "Solarium",
  "Children's pool",
  "Extra long beds",
  "Skiing",
  "Concierge",
  "Laundry service",
  "Nature walk",
  "Waxing services",
  "Picnic area",
  "Walking tours",
  "Special diet menus",
  "Multi-storey parking",
  "Karaoke",
  "Hand massage",
  "24-hour front desk",
  "Steam room",
  "Private pool",
  "Darts",
  "Evening entertainment",
  "Electric kettle",
  "Self-service laundry",
  "Adults only",
  "Room service",
  "Beach",
  "24-hour check-in option",
  "Safe",
  "Wardrobe/closet",
  "Dining room",
  "Paid Wi-Fi",
  "Rooftop pool",
  "Paid internet",
  "Pool",
  "Free shuttle or taxi services",
  "Free stay for children",
  "Private entrance/exit",
  "Ski rental",
  "Currency exchange",
  "Restaurant",
  "Coffee/tea maker",
  "Additional bathroom",
  "Free High-Speed Internet (WiFi)",
  "Express check-in/check-out",
  "Door attendant",
  "Animation team",
  "Adult pool",
  "Bicycles available",
  "Books for children",
  "Shuttle bus service",
  "Water slide",
  "Parking",
  "Small kitchen",
  "Canoeing trip (off-site)",
  "Non-smoking rooms",
  "Fishing",
  "Water park (off-site)",
  "Free tea",
  "Poolside bar",
  "Oven",
  "Radio",
  "Sunbathing terrace",
  "Market",
  "Private balcony",
  "Canoeing",
  "Slow-flowing river in the water park",
  "Music",
  "Indoor pool",
  "Turkish bath",
  "Infirmary",
  "Indoor play area for children",
  "Separate dining room",
  "Pool/beach towels",
  "Ski-in/ski-out",
  "Cable/satellite TV",
  "On-site private parking (surcharge)",
  "Free parking",
  "Mini golf",
  "Free Instant Coffee",
  "Free internet",
  "Family rooms",
  "Aerobics (off-site)",
  "Bidet",
  "Valet parking service",
  "Public Wi-Fi",
  "Tennis court",
  "Shared bathroom",
  "Heated pool",
  "Bottled water",
  "Kid-friendly TV channels",
  "Interconnecting rooms available",
  "Full body massage",
  "Jacuzzi",
  "Foot massage",
  "Shallow pool",
  "Outdoor dining area",
  "Free Wi-Fi at the business center",
  "Swimming pool toys",
  "On-site paid public parking",
  "Pool with railing",
  "Kitchenware",
  "Tennis court (off-site)",
  "Snorkeling",
  "Lounge",
  "First aid kit",
  "Honeymoon suite",
  "Wi-Fi",
  "Children's Activities (Kid-friendly/Family-friendly)",
  "Fireplace",
  "BBQ areas",
  "Jacuzzi bathtub",
  "Bowling",
  "Newspaper",
  "Stovetop",
  "Table tennis",
  "Nightclub/DJ",
  "Laptop safe",
  "Ironing service",
  "Squash (off-site)",
  "Pool view",
  "Garden",
  "Foot bath",
  "Pets allowed (Dogs/Pets Allowed)",
  "City view",
  "Sun terrace",
  "Suites",
  "Complimentary welcome drink",
  "Coffee shop",
  "Diving",
  "Outdoor play equipment for children",
  "iPod dock",
  "Ocean view",
  "Shops",
  "Street parking",
  "Washing machine",
  "Work desk",
  "Board games/puzzles",
  "Shared lounge/TV area",
  "Free wired internet in the business center",
  "Iron",
  "Video game console",
  "Hypoallergenic room",
  "Phototherapy",
  "Flat-screen TV",
  "Breakfast in room",
  "Seating area",
  "VIP room amenities",
  "Baby high chair available",
  "Personal trainer available",
  "Umbrella",
  "Business section with internet access",
  "Ski school",
  "Stroller",
  "Wine/champagne",
  "Sauna",
  "Table tennis (off-site)",
  "Yoga room",
  "Makeup services",
  "Dishwasher",
  "Separate living room",
  "Car rental",
  "Neck massage",
  "Fitness center with gym/workout room",
  "Airport transportation service",
  "On-site ATM",
  "Massage chair",
  "Duty room",
  "Walk-in shower",
  "Air conditioning",
  "Children's meals",
  "Facials",
  "Breakfast available",
  "Wake-up service/alarm clock",
  "Badminton",
  "Bar/lounge",
  "Smoking rooms available",
  "Fitness classes",
  "Spa",
  "Fitness/spa changing rooms",
  "Swim-up bar",
  "Luggage storage service",
  "Horse riding",
  "Mosquito net",
  "Vending machine",
  "Electric vehicle charging station",
  "Private bathrooms",
  "Babysitting",
  "Water park",
  "Non-smoking hotel",
  "Archery (off-site)",
  "Windsurfing",
  "Private beach",
  "Yoga classes",
  "Couples massage",
  "Boat tour",
  "Happy hour",
  "Soundproof rooms",
  "Bicycle tours",
  "Free breakfast",
  "Golf course",
  "Blackout curtains",
  "Bathrobes",
  "Pay-per-view movies",
  "Tile/marble floor",
  "Meeting rooms",
  "Sun loungers/beach chairs",
  "Electric blanket",
  "Taxi service",
  "Pool with a view",
  "Bicycle rental",
  "Shared kitchen",
  "Outdoor furniture",
  "24-hour security",
  "Clothes dryer",
  "Mountain view",
  "Private lounge facility",
  "Mini bar",
  "Nearby public free parking",
  "Free nearby private parking",
  "Bathroom/shower",
  "Buffet suitable for children",
  "Free airport transportation",
  "DVDs",
  "Body mask",
  "Outdoor fireplace",
  "Pool with shallow end",
  "Gift shop",
  "Telephone",
  "Hair Dryer",
  "Iconic point view",
  "Clothes rack",
  "Bowling (off-site)",
  "Butler service",
  "Massage",
  "Buffet breakfast",
  "Billiards",
  "Microwave oven",
  "Place of worship",
  "Water sports equipment rental",
  "Conference room",
  "Casino and Gambling",
  "Internet",
  "Outdoor pool",
  "Photocopy/fax services at the business center",
  "Kids' club",
  "Nearby paid private parking",
  "Outdoor bath",
  "Rooftop bar",
  "Sofa",
  "Secure parking",
  "Aerobics",
  "Free toiletries and personal care products",
  "Dry cleaning",
  "Hot spring bath",
  "Nearby paid public parking",
  "Air purifier",
  "Sun umbrellas",
  "Manicure",
  "Saltwater pool",
  "Rooftop terrace",
  "Archery",
  "Snack bar",
  "Refrigerator",
];

export const RESTAURANT_FILTER = {
  5: false,
  4: false,
  3: false,
  2: false,
  breakfast: false,
  brunch: false,
  lunch: false,
  dinner: false,
  cheap: false,
  average: false,
  expensive: false,
  vegeterian: false,
  "gluten-free": false,
  vegan: false,
  big_group: false,
  romantic: false,
  "Yöresel mutfak": false,
  Nevşehir: false,
  Bursa: false,
  Çanakkale: false,
  İzmir: false,
  Antalya: false,
  İstanbul: false,
  Ankara: false,
  Aydın: false,
  Balıkesir: false,
  Muğla: false,
  "Tıbbi gıdalar": false,
  Akdeniz: false,
  Venezuela: false,
  "Amerikan Yerli": false,
  "Güney İtalya": false,
  Avrupa: false,
  Nijerya: false,
  "Sri Lankalı": false,
  Brezilya: false,
  "Biftek Restoranı": false,
  Alman: false,
  "Japon Füzyonu": false,
  Meksika: false,
  Romanya: false,
  Hawai: false,
  Campania: false,
  İspanyol: false,
  İtalyan: false,
  İskoç: false,
  Fujian: false,
  Latin: false,
  Pizza: false,
  Filipinler: false,
  Ekvador: false,
  "Kosta Rika": false,
  Kolombiya: false,
  Arap: false,
  Asur: false,
  Füzyon: false,
  Türk: false,
  "Yemekli barlar": false,
  Ermeni: false,
  Jamaika: false,
  İskandinav: false,
  İsviçre: false,
  "Kuzey İtalya": false,
  Ortadoğu: false,
  "Japon tatlı dükkânı": false,
  Lübnan: false,
  Lombard: false,
  Güneybatı: false,
  Felemenk: false,
  Rus: false,
  Mangal: false,
  "Cajun ve Creole": false,
  Yunan: false,
  "Bira restoranları": false,
  Hırvat: false,
  Polonya: false,
  Etiyopya: false,
  Endonezya: false,
  "Sokak Yemekleri": false,
  Barbekü: false,
  Katalan: false,
  Yunnan: false,
  Fas: false,
  Tayvan: false,
  Avusturya: false,
  İran: false,
  Asya: false,
  Sağlıklı: false,
  Çin: false,
  "Fast Food": false,
  "Doğu Avrupa": false,
  "Deniz Mahsülleri": false,
  Gürcü: false,
  "Brew Pub": false,
  Bar: false,
  Azerbaycan: false,
  Kafe: false,
  Fransız: false,
  Emilia: false,
  Liguria: false,
  Şarküteri: false,
  Xinjiang: false,
  Moğol: false,
  Sloven: false,
  Şili: false,
  Afrika: false,
  Danimarka: false,
  Vietnam: false,
  Arjantin: false,
  Suşi: false,
  Peru: false,
  Karayipler: false,
  Portekiz: false,
  Balti: false,
  Çorbalar: false,
  Shojin: false,
  Ukrayna: false,
  İsveç: false,
  "Şarap Barı": false,
  Tunus: false,
  "Güney Amerika": false,
  Polinezya: false,
  Macar: false,
  Lokanta: false,
  Malezya: false,
  Napoli: false,
  Arnavut: false,
  "Pekin mutfağı": false,
  Belçika: false,
  Sicilya: false,
  Kafkas: false,
  İrlanda: false,
  Amerikan: false,
  Yöresel: false,
  İsrail: false,
  Pakistan: false,
  Avustralya: false,
  Özbek: false,
  Cezayir: false,
  Lazio: false,
  Letonya: false,
  Guatemala: false,
  "Orta Asya": false,
  Norveç: false,
  Küba: false,
  Hint: false,
  Çağdaş: false,
  "Orta İtalya": false,
  Kore: false,
  Gastropub: false,
  Japon: false,
  "Orta Amerika": false,
  Romana: false,
  Afkan: false,
  Kanada: false,
  Bahama: false,
  İngiliz: false,
  "Orta Avrupa": false,
  Toskana: false,
  Tibet: false,
  Nepal: false,
  Sardinya: false,
  "Kyoto mutfağı": false,
  Çek: false,
  "Meyve dükkânları": false,
  Kamboçya: false,
  Mısır: false,
  Tayland: false,
  Bangladeş: false,
  Gal: false,
  Uluslararası: false,
};

export const HOTEL_FILTER = {
  Radyo: false,
  İnternet: false,
  "Çocuklara ücretsiz konaklama": false,
  "Çocuk Aktiviteleri (Çocuğa/Aileye Uygun)": false,
  "Ismarlanabilen filmler": false,
  "Bisiklet kiralama": false,
  "Dağ manzaralı": false,
  "Oda hizmeti": false,
  "Bulaşık makinesi": false,
  "Ücretsiz internet": false,
  Lostra: false,
  "Şehir manzaralı": false,
  "Ayrı oturma odası": false,
  "Kapalı havuz": false,
  "Çocuklar için kitaplar": false,
  Dalış: false,
  "Okyanus manzarası": false,
  "Ayrı yemek salonu": false,
  "Çocuk yemekleri": false,
  "Çamaşır kurutma makinesi": false,
  "Özel balkon": false,
  "Barbekü alanları": false,
  "Ortak mutfak": false,
  Cibinlik: false,
  Concierge: false,
  "Bisiklet mevcut": false,
  Masaj: false,
  "Kuru temizleme": false,
  "Birbirine açılan odalar mevcut": false,
  "DVD’ler": false,
  "İnternet Bağlantılı İş Amaçlı Bölüm": false,
  "Ses geçirmez odalar": false,
  Buzdolabı: false,
  "Çocuklara uygun büfe": false,
  "Çocuklar için oyun alanı": false,
  "Ücretsiz Yüksek Hızda İnternet (WiFi)": false,
  "Güneşlenme alanı": false,
  "Çamaşır yıkama hizmeti": false,
  "Yakınlarda halka açık ücretsiz otopark": false,
  "Cadde üzerinde park": false,
  "Kablolu/uydu bağlantılı TV": false,
  "Balık tutma": false,
  "Evcil Hayvan Kabul Edilir (Köpeğe/Evcil Hayvanlara İzin Verilir)": false,
  "Uyandırma servisi/çalar saat": false,
  Sauna: false,
  Bahçe: false,
  "Spor Salonlu/Spor Odalı Fitness Merkezi": false,
  "Servis otobüsü hizmeti": false,
  "Ekstra uzun yataklar": false,
  "Bagaj saklama hizmeti": false,
  Bornoz: false,
  "Jakuzili küvet": false,
  "Piknik alanı": false,
  "İş merkezinde fotokopi/faks": false,
  "Saç kurutma makinesi": false,
  "Tam vücut masajı": false,
  "Masa tenisi": false,
  "Hızlı giriş/çıkış": false,
  "Yetişkin havuzu": false,
  "Set Üstü Ocak": false,
  "Tekne turu": false,
  "Hava temizleme cihazı": false,
  "Çocuklar için açık hava oyun ekipmanı": false,
  "Banyo/duş": false,
  Revir: false,
  "Bebek sandalyesi mevcut": false,
  "Gece Kulübü/DJ": false,
  "Gece eğlencesi": false,
  Puset: false,
  "Kahvaltı mevcut": false,
  "Dizüstü bilgisayar kasası": false,
  "Şezlonglar/plaj sandalyeleri": false,
  "Tesis içi ATM": false,
  Klima: false,
  "Ortak oturma/televizyon izleme alanı": false,
  "Küçük mutfak": false,
  "Ücretsiz Hazır Kahve": false,
  "Balayı süiti": false,
  Spa: false,
  "Rüzgar sörfü": false,
  "Yerle aynı hizada duş": false,
  "Bebek bakımı": false,
  "Havaalanı ulaşım hizmeti": false,
  "Yemek salonu": false,
  "Isıtmalı havuz": false,
  "Çalışma masası": false,
  "Görevli odası": false,
  "Araba kiralama": false,
  "Konferans salonu": false,
  "Çocuklara uygun televizyon kanalları": false,
  "Çatı barı": false,
  Hamam: false,
  Gazete: false,
  "Çamaşır makinesi": false,
  "Karo/mermer zemin": false,
  "Ayak masajı": false,
  "Bisiklet turları": false,
  "Gardırop/elbise dolabı": false,
  "Çatı katı terası": false,
  "Elbise askısı": false,
  "Ek banyo": false,
  "İndirimli içki saati": false,
  Müzikler: false,
  "Simgesel nokta manzarası": false,
  Market: false,
  "Hediyelik eşya dükkanı": false,
  "Fitness/spa soyunma odaları": false,
  "Güneş şemsiyeleri": false,
  "Alerjensiz oda": false,
  "Aile odaları": false,
  Telefon: false,
  "Şişe suyu": false,
  Kasa: false,
  "Havuz kenarı barı": false,
  "Doğa yürüyüşü": false,
  "Açık havuz": false,
  "Döviz bozdurma": false,
  "VIP oda olanakları": false,
  Dart: false,
  "Oturma alanı": false,
  "Düz Ekran Televizyon": false,
  "Oyun salonu": false,
  "İlk yardım çantası": false,
  "Kahve dükkanı": false,
  "Ütü hizmeti": false,
};
